apiVersion: v1
kind: PersistentVolume
metadata:
  name: katech-xlabeller-pv
  namespace: katech-xlabeller
spec:
  storageClassName: katech-dataset
  volumeMode: Filesystem
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteMany
  cephfs:
    monitors:
      - 10.10.30.151:6789
      - 10.10.30.152:6789
      - 10.10.30.153:6789
      - 10.10.30.154:6789
      - 10.10.30.155:6789
    path: /kadap-portal
